language: go

go:
  - master

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.55.2/hugo_0.55.2_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb

script:
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  repo: withlin/blog
  target-branch: gh-pages
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
